#
# Copyright (c) 2017 Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
language: java
# the secure configurations in env: section is for BINTRAY_USER=<USER> and BINTRAY_KEY=<KEY> properties
# which will be used for publishing artifacts to snapshot repository
env:
  global:
  - GRADLE_OPTS="-Xms128m"
  - secure: "HOWQF8zJrWYftBCsu/lnmG1gUN7jKu3dEMX7kc76jUugOMUbjW2BtQguG7cuI4NCz3XLBeYa9ZQMg1snvkWJcpKH/vpTLh7Mf6eV2h1/ocfCnFw/iQw1Y/Tsgr3jyr/usdGiClpHrzV/OC6p/n0shJmawfK40rSn1P3xiRdYOLHDd/vBkwxCbcS6mOOlLrKG5lXJ2GOGBWGWmXhbBCCy6XWJzF2+CFf02ieL6SvkxNwIlKrif8cYSzV+lAoxuoVPjK9qMbB3r/BD6+8vGjIAX4MgvWRGkok/tfuCBE+PQ1mJIJBKzq3T1Hy/0czWClNbTAAZKdSTErR4REdViZrddddr39olzn7Y7GYCcG/cnpfGnhmeQQ/9ddvH3do6Tb3rh/nxs2PeFuofDwoWLlwke6oed/yhI9tEZzBGdVW6y6HCcfYfvaliaSIB24SDBA8I2K/m2oay8f2gbDyVeBRK6pCEDCklbPGPBjVVfhqosgbFcZfCYO4WVGh3c1j+siT1yHNxsiVSYT6riIzA5D10o/8o+b/ex2AS6lmtQR2L9rpp+zzm7u1scvsXu6dUN/fPZqBZb3/kY8kh7xkoNCc3bYXOy3I76xu756FpR6VJkU1UkRDjT9cepza1A3YDvyAgEClseTFBKE+RSiBh9v7PVcW4oItJ+fRRvnakhroYByM="
  - secure: "VH9F5YUSBh16A3gmTq/vE5Qt/yl+p8+TwrOIeELF7YvYS6915+Ju0BiLwq6EvJ2eZf3OZi5bdmXgdiuUHeyYtHCv4LK/RhClOeF0NtqlltXPUPKcoA+urgsT+UKQ7uSFgMaHhG+jDDpueJjKqNwmuxBpe4AcumCilmF/tM0EZucGD40JjoAJBQydLygmmoucp5KMNAr+xrp3JNC10T3HvtwTwnxwk00deEiHY5BctyIaS63hqFml1pIF69bL7+lsVfaw8IvtFBypGvcJPiUSbQVlj9zSU7ur+q7be/KUtvL99X+ZgyoGgrGmrE/qKubb6S9G8YtMWSy57CE1RHcZNjXMOIQ0PJlRMLpzH1KZQLHn3Pnu/vN/tAkSCgLExVo3DOteaanT0ve+Nxp8feNORb0OtKvlcpLgB7ke+VziZRx0Rlhvao2DmjIcoe9Re8uUszLyQf+c6rpiiCe9L1N6V+6WBSB4nYEe/s6kQ/dsu3St2ttePKXdsV2QhhrsupBv2qk8LL0AFJT9ECqAqRHQkVCB2EJLd/zRNdSSwJ2xWhJ42t6PKSfLrPXlLQKN1GCLSp+6io/6p0RD2dvVrwY5gtD309krKOdD9nqGvbZlIm1oq/zKuH0BoKN5JQ4qCI8ju9J0RjMD53vtQnMbD7mKVE0iaS1Q8Rk+2fMDZGMEkLo="

cache:
  directories:
  - ".gradle"
  - "$HOME/.gradle"

stages:
  - name: build
  - name: snapshot
    if: branch = master AND NOT (type = pull_request)

jobs:
  include:
    - stage: build
      script: ./gradlew build
    - stage: snapshot
      script: ./gradlew publishToRepo -PpublishUrl=jcenterSnapshot -PpublishUsername=$BINTRAY_USER -PpublishPassword=$BINTRAY_KEY

notifications:
  slack:
    matrix:
      secure: SR0arFY2SVk+7nNjwYVnrmZfKk2XZTxbyfHaAGf6iAbPLdfVijgTwy66AhIUQJgMvL6mDFSVrzgHEK/246/folweGNTjzW4gPZtJXXfvTxzPXPe6HXhRB8zRbNFKzmPjuDoVKJjMvfq3X+JTI/plKR8wIQJvCeoxjc+U9mfWPO63HS4GRueSLkiKrKf5XpEPmwc4i6Z9ZVQRM2G1J2hGo+6ISZEoMRRXTbHZtGMxQGqsV0heuMQ4ebxcjHjvmf8Zm4Qn76foLrHSNgBLqbB6/Tm9SJY1FjsDXp5aBLkHgYpT5szkQTA0Xm9Zur3fGSFeOjJCuwKhqoX2KXQwT2OF/rEmpQWBwHCvoq9HLW1I7uXZgAhfccmhXkUswoNIJZJjq0yNUWupdmSjkMPqQBz/dyJ3nEIWh7DYdd/NxSO1L+GOOtRhYq015GakjFVdJW5Wibs73dNu6q4zlkdWSq7VutTyqGEJJjw/Z8mSsF0LneT0nM+EGEN3aovLlyd9G7kRTZ/baq4YXmy2mauHUNPAt9z5jSWxZ5mHldfn5vp3xU+XXuiNUYCLgYX8z6Y2bggc9IRWiT5SZBd4/vfMBWRk6uFamPKPI6AYRYErGHeHsmohgtYyV2qWUfVZBqflGU5dpSlGnXX7/msO2oytSgrMs2xWWVspNwzbSg83sjcZiXw=
    rooms:
      secure: crNIo08lzOP05MEUg3B+riVPbI3K2Y56oQ4f9qaxQ4vod3MAYdSuWF9EbCvMKYM93eboHHXT+QecXLUs6QJ6m07komFawSCIPMnWTUYr0qHygCnV6wc7u+8rZyNeI4EgCn8vlb4/WjA6I3hOuQUSoVgti7LdNe2V0fXXHJiHiduqtSDG5RFIc79ceYUbZF+ouxlGY7IKQ8UZTozMQzl8Gmm4lVAYmBDlv7g9jM3Q8OqC0IOAh718413KtHH5cPfeGTsRspZOL5TxwYX61hrQAnXbecVOvV2R7nYkfwsDCR/xMj846egN1wrlwW1P65a18q2pMqpBryuhjxHR3jWm+WIxGqu5Is330umIbr80qFAYMPx6pE2pk3FUFFJfAfFSwDULRESAO8R99ZHSuy2RYDWiP9A4HwcXHFnzVjxrbctamZotNEBoRYEsc394BxF3i8ft3u2k/IBqiPCPXlmGKzIBK43Ou0AdRF/qbzZxIRCSJxcYV8S7+YeuaR6/5bb8uAJ9RfwkaoWOxjV03OE/nZSs/2kIyXKp0WmCfVmPTKx6NRqSldY5eyjP69nCFjQUZ4CTHOFvXh8ShExJ/p3oIrIIn1zH1teo80EokzrX5B4vb7ORWBZ4kHKzpei9+HVWFUIVLGFQtY8cz0E3wGaAeEPP7jcxv+C4H+YwVviMCDg=
  email:
  - bo.yang@emc.com
  - eron.wright@emc.com
  - flavio.junqueira@emc.com
  - lida.he@emc.com
