language: java
# the secure configurations in env: section is for BINTRAY_USER=<USER> and BINTRAY_KEY=<KEY> properties
# which will be used for publishing artifacts to snapshot repository
env:
  global:
  - GRADLE_OPTS="-Xms128m"
  - secure: "EPL076YzDvzRIThkh5pbpgd/59vONUsncWg7uESuY/7P7ZVnksUFoE20/vQNo40OTgukkjgnTymb0uJ9jWFpQOnNw+LzdvhC4BtPSAg4SlEuIsOhj6qPdvYe8XhGZj0Z0yGcP7dwu18pgaNSTJ1iVRjPXlysgYOwl0JF/XcL7yzi486JTmmaFlsKUz9sikO00JUwml32DmyUCMsdgtfzKx4CvSepsFjgDlACErul+/kKButS74a9SzaBfLwxI1TFjni9JEMZGcK9pNP6Mi6//1kZcG2W0GWkmAqPo73VvBSaSR/zso/5mJNSsBv7f4eOwIh/Nkv74g4xmVds6wHxCQC77SedGpvVcXnmGVdXHL17sCOenuc1R70K2Qq00hMaDz/2kG497Estd96kpVUav680p8N8WPjEbHqfDY3k+/8MmBce8NWkPGUy4XdF4eJxLUJ8GEXRzR2v9JDY9A2gcNmSC6rwf0VedbopQ/fE5k8CKgvt9eZQM2nJE5ZzObakVssvYNNIexK0NprH0hQMLt68sLBAN7H8M57wbZSUEZD3e52SesK8h0xZIYty1leaUx/G/yo1wxOGNC4fGqyjPYNf04zDv/gnK11eeJBOu+t9T07PVn7XWBg0CdoX4XY+1Rlp8yWvQINXWwYSMhUu+xU1KyCp67qTD7MadZ/OjLE="
  - secure: "CuLbIV4oqk9W1mNdy9Dz/YmOW/638ufJf+B83lxCky6l+Us6p5sGAyv+GZUWtYKpExFah3+lC6Fp8DOlQOsSpNz50bSEFzOWRKDyLui2btS06wXjPhp5M+dBZgPolTrrxb6BM7gGcA0sPkpFbDufblF7E/wmMiBUePsCnHiP3mGlR+Zxk/i44R3Ooy4ScoPGH8kB6i5S0YEF26WV+qDOv3/qRuMAQpCqWhovIvdNps/aZwvYYYvYLrx3sj/+menay/D23i1W2r4w4hdF2oLekkT+qY22dajTKkE+RpoIKDC1YYIz22jnSUN68DRQipsXD/S3IfK2HacvveopdDytHHy+RfYGvuToMnj7rwXf3ycSTLKYK0/kN4HVsNl4Nq1b9CuxZP5YETU51o0bX1BRw8H5cmGhrzZfmcouYEc7KMl51S+3ksP3fuM5ZH2iej3LVVk5sT19sDwo/xcbXZg7Pv2sCMJdnf9YSfhpXIiqC3ZNIA5sWJLQUJtccUCvlu76/6K8y+34Gz4YJXGYZHNQl+0g+b17dnhgJEG2hDV0cFlu7TJqVwFRijbRpRMitQng5+/cBYCiKPYxfg/iaqFxNfJoJXPe2QaYxkt72FzybtCQvNjlFAzf/KRs41jU9o+ZFBaD4X4jmdPRUouwtGP6k7QxnRcnrhiUHncbewcnhE8="

cache:
  directories:
  - ".gradle"
  - "$HOME/.gradle"

stages:
  - name: build
  - name: snapshot
    if: branch = master AND NOT (type = pull_request)

jobs:
  include:
    - stage: build
      script: ./gradlew build
    - stage: snapshot
      script: ./gradlew publishToRepo -PpublishUrl=jcenterSnapshot -PpublishUsername=$BINTRAY_USER -PpublishPassword=$BINTRAY_KEY

notifications:
  slack:
    matrix:
      secure: SR0arFY2SVk+7nNjwYVnrmZfKk2XZTxbyfHaAGf6iAbPLdfVijgTwy66AhIUQJgMvL6mDFSVrzgHEK/246/folweGNTjzW4gPZtJXXfvTxzPXPe6HXhRB8zRbNFKzmPjuDoVKJjMvfq3X+JTI/plKR8wIQJvCeoxjc+U9mfWPO63HS4GRueSLkiKrKf5XpEPmwc4i6Z9ZVQRM2G1J2hGo+6ISZEoMRRXTbHZtGMxQGqsV0heuMQ4ebxcjHjvmf8Zm4Qn76foLrHSNgBLqbB6/Tm9SJY1FjsDXp5aBLkHgYpT5szkQTA0Xm9Zur3fGSFeOjJCuwKhqoX2KXQwT2OF/rEmpQWBwHCvoq9HLW1I7uXZgAhfccmhXkUswoNIJZJjq0yNUWupdmSjkMPqQBz/dyJ3nEIWh7DYdd/NxSO1L+GOOtRhYq015GakjFVdJW5Wibs73dNu6q4zlkdWSq7VutTyqGEJJjw/Z8mSsF0LneT0nM+EGEN3aovLlyd9G7kRTZ/baq4YXmy2mauHUNPAt9z5jSWxZ5mHldfn5vp3xU+XXuiNUYCLgYX8z6Y2bggc9IRWiT5SZBd4/vfMBWRk6uFamPKPI6AYRYErGHeHsmohgtYyV2qWUfVZBqflGU5dpSlGnXX7/msO2oytSgrMs2xWWVspNwzbSg83sjcZiXw=
    rooms:
      secure: crNIo08lzOP05MEUg3B+riVPbI3K2Y56oQ4f9qaxQ4vod3MAYdSuWF9EbCvMKYM93eboHHXT+QecXLUs6QJ6m07komFawSCIPMnWTUYr0qHygCnV6wc7u+8rZyNeI4EgCn8vlb4/WjA6I3hOuQUSoVgti7LdNe2V0fXXHJiHiduqtSDG5RFIc79ceYUbZF+ouxlGY7IKQ8UZTozMQzl8Gmm4lVAYmBDlv7g9jM3Q8OqC0IOAh718413KtHH5cPfeGTsRspZOL5TxwYX61hrQAnXbecVOvV2R7nYkfwsDCR/xMj846egN1wrlwW1P65a18q2pMqpBryuhjxHR3jWm+WIxGqu5Is330umIbr80qFAYMPx6pE2pk3FUFFJfAfFSwDULRESAO8R99ZHSuy2RYDWiP9A4HwcXHFnzVjxrbctamZotNEBoRYEsc394BxF3i8ft3u2k/IBqiPCPXlmGKzIBK43Ou0AdRF/qbzZxIRCSJxcYV8S7+YeuaR6/5bb8uAJ9RfwkaoWOxjV03OE/nZSs/2kIyXKp0WmCfVmPTKx6NRqSldY5eyjP69nCFjQUZ4CTHOFvXh8ShExJ/p3oIrIIn1zH1teo80EokzrX5B4vb7ORWBZ4kHKzpei9+HVWFUIVLGFQtY8cz0E3wGaAeEPP7jcxv+C4H+YwVviMCDg=
  email:
  - bo.yang@emc.com
  - eron.wright@emc.com
  - flavio.junqueira@emc.com
  - lida.he@emc.com
